# Generated by Django 5.1.1 on 2025-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
