# Generated by Django 5.2 on 2026-05-22 04:07

import django.db.models.deletion
import expense_app.encrypted_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0004_alter_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_amount',
            field=expense_app.encrypted_fields.EncryptedDecimalField(decimal_places=2, max_digits=10, max_length=256),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_place',
            field=expense_app.encrypted_fields.EncryptedCharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=expense_app.encrypted_fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, max_length=256),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('label', models.CharField(default='Fingerprint', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
